name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # This'll run both `expect`s and `./tests.roc` for us.
  test:
    uses: niclas-ahden/roc-workflows/.github/workflows/test.yml@v1
